@startuml
!define QtWidgets ../../../Qt/Widgets
!include LayoutViewItems.puml
!include QtWidgets/QGraphicsScene.puml

class LayoutViewSegmentLayout {
}

class CreateLayoutViewGraphicsScene {
}

CreateLayoutViewGraphicsScene ..> SectionGraphicsItem
CreateLayoutViewGraphicsScene ..> SegmentGraphicsItem
CreateLayoutViewGraphicsScene --> QGraphicsScene
CreateLayoutViewGraphicsScene *--> LayoutViewSegmentLayout

' note left of CreateLayoutViewScene : This is a use case\nor interactor.

hide QObject
hide QGraphicsItem
hide QGraphicsItemGroup
hide LayoutGraphicsItem

@enduml
