@startuml
!define QtWidgets ../../../Qt/Widgets
!define MdtElf ../../../Mdt/ExecutableFile/Elf
!include QtWidgets/QGraphicsItemGroup.puml
!include MdtElf/SectionHeader.puml

class LayoutGraphicsItem {
  +LayoutGraphicsItem()
}

QGraphicsItemGroup <|-- LayoutGraphicsItem


class SectionGraphicsItemData {
}

SectionGraphicsItemData ..> Mdt.ExecutableFile.Elf.SectionHeader


class SectionGraphicsItem {
}

LayoutGraphicsItem <|-- SectionGraphicsItem
SectionGraphicsItem *--> SectionGraphicsItemData


class SegmentGraphicsItem {
}

LayoutGraphicsItem <|-- SegmentGraphicsItem

hide methods
hide attributes

@enduml
