@startuml
!include HeaderTable_LayoutView_Map.puml
!include TableViews.puml

class MainWindow {
}

class LayoutViewGraphicsScene {
}


class CreateSectionHeaderTableModel {
}

class SomeCreate {
}

' SomeCreate --> CreateLayoutViewScene
SomeCreate --> CreateSectionHeaderTableModel
SomeCreate --> "2" HeaderTableGraphicsItemMap

class MainWindowController {
}

MainWindowController *--> LayoutViewGraphicsScene
MainWindowController *--> SectionHeaderTableModel
MainWindowController *--> ProgramHeaderTableModel
MainWindowController *--> "2" HeaderTableGraphicsItemMap
MainWindowController --> MainWindow

' MainWindowController --> SomeCreate

hide methods
hide attributes

@enduml
