@startuml
!define QtCore ../../Qt/Core
!include QtCore/QObject.puml

namespace Mdt.ExecutableFile {

  class AbstractExecutableFileIoEngine {
  }

}

QObject <|-- Mdt.ExecutableFile.AbstractExecutableFileIoEngine

@enduml
