@startuml
!include ExecutableFileIoEngineImplementationInterface.puml
!include Elf/FileIoEngine.puml

namespace Mdt.ExecutableFile {

  class ElfFileIoEngine {
  }

  ExecutableFileIoEngineImplementationInterface <|-- ElfFileIoEngine
}

Mdt.ExecutableFile.ElfFileIoEngine *--> Mdt.ExecutableFile.Elf.FileIoEngine

@enduml
