@startuml
!define QtCore ../../Qt/Core
!include QtCore/QObject.puml

namespace Mdt.ExecutableFile {

  class ExecutableFileIoEngineImplementationInterface {
  }

}

QObject <|-- Mdt.ExecutableFile.ExecutableFileIoEngineImplementationInterface

@enduml
