@startuml
!define QtCore ../../Qt/Core
!include ExecutableFileIoEngineImplementationInterface.puml
!include QtCore/QObject.puml

namespace Mdt.ExecutableFile {

  class ExecutableFileIoEngine {
  }

  ExecutableFileIoEngine *--> ExecutableFileIoEngineImplementationInterface
}

QObject <|-- Mdt.ExecutableFile.ExecutableFileIoEngine

@enduml
