@startuml
!include ExecutableFileIoEngineImplementationInterface.puml
!include Pe/FileReader.puml

namespace Mdt.ExecutableFile {

  class PeFileIoEngine {
  }

  ExecutableFileIoEngineImplementationInterface <|-- PeFileIoEngine
}

Mdt.ExecutableFile.PeFileIoEngine *--> Mdt.ExecutableFile.Pe.FileReader

@enduml
